Enhancement/es6 porting
ericluii/AmalgamateJS pull request #1
Opened 2016-12-11 15:38 UTC by btruhand

Should be good with node >= 6.0.0. I tested on 6.0.0 minimum and 6.9.2 highest (LTS version)

2016-12-12 17:13 UTC, ericluii commented
LGTM (Y) Thanks Btara

2016-12-12 17:14 UTC, ericluii requested changes

2016-12-12 17:14 UTC, ericluii commented on package.json
> +	"engines": { "node" : ">=6.0.0" },
Oh wait - indent 2 instead of 4?

2016-12-13 11:50 UTC, btruhand commented on package.json
> +	"engines": { "node" : ">=6.0.0" },
Addressed in latest commit

2016-12-19 03:28 UTC, merged